version: '3'
services:
  web:
    build: .
    image: r4victor/hierarchy
    container_name: hierarchy
    depends_on:
      - postgres
    restart: always
    volumes:
      - ./app:/usr/src/hierarchy/app
      - ./tests:/usr/src/hierarchy/tests
    environment:
      - FLASK_ENV
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
      - POSTGRES_PORT=5432
    ports:
      - 8888:8000
  postgres:
    image: postgres
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    ports:
      - 5432:5432

    